# docker-compose.yaml placed at root of the project
version: '3'
services:
  web:
    container_name: "farosArgentinos"
    build:
      context: .
      dockerfile: /

    ports:
      - "8000:8000"
